### ISSUE TITLE
Deploy to Netlify - build error

### ISSUE THREAD

**Issue by JorisKok** [mxstbr/nextjs-decap-cms-blog-template#1]
I'm getting the following build error when pressing the https://decapcms.org/docs/start-with-a-template/ -> Deploy to Netlify button. 

The created repo in my account is empty, not sure if that could be an issue?

```
9:27:45 AM: Netlify Build                                                 
9:27:45 AM: ────────────────────────────────────────────────────────────────
9:27:45 AM: ​
9:27:45 AM: ❯ Version
9:27:45 AM:   @netlify/build 29.12.1
9:27:45 AM: ​
9:27:45 AM: ❯ Flags
9:27:45 AM:   baseRelDir: true
9:27:45 AM:   buildId: 648eb1d8033576082568d5b1
9:27:45 AM:   deployId: 648eb1d8033576082568d5b3
9:27:45 AM: ​
9:27:45 AM: ❯ Current directory
9:27:45 AM:   /opt/build/repo
9:27:45 AM: ​
9:27:45 AM: ❯ Config file
9:27:45 AM:   /opt/build/repo/netlify.toml
9:27:45 AM: ​
9:27:45 AM: ❯ Context
9:27:45 AM:   production
9:27:45 AM: ​
9:27:45 AM: build.command from netlify.toml                               
9:27:45 AM: ────────────────────────────────────────────────────────────────
9:27:45 AM: ​
9:27:45 AM: $ npm run export
9:27:45 AM: > my-app@0.1.1 export
9:27:45 AM: > next build && next export -o ./dist
9:27:45 AM: Browserslist: caniuse-lite is outdated. Please run:
9:27:45 AM: npx browserslist@latest --update-db
9:27:45 AM: Why you should do it regularly:
9:27:45 AM: https://github.com/browserslist/browserslist#browsers-data-updating
9:27:45 AM: node:internal/errors:490
9:27:45 AM:     ErrorCaptureStackTrace(err);
9:27:45 AM:     ^
9:27:45 AM: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /opt/build/repo/node_modules/next/node_modules/postcss/package.json
9:27:45 AM:     at new NodeError (node:internal/errors:399:5)
9:27:45 AM:     at exportsNotFound (node:internal/modules/esm/resolve:361:10)
9:27:45 AM:     at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
9:27:45 AM:     at resolveExports (node:internal/modules/cjs/loader:565:36)
9:27:45 AM:     at Module._findPath (node:internal/modules/cjs/loader:634:31)
9:27:45 AM:     at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
9:27:45 AM:     at Module._load (node:internal/modules/cjs/loader:920:27)
9:27:45 AM:     at Module.require (node:internal/modules/cjs/loader:1141:19)
9:27:45 AM:     at require (node:internal/modules/cjs/helpers:110:18)
9:27:45 AM:     at 552 (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
9:27:45 AM:     at __nccwpck_require__ (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
9:27:45 AM:     at 270 (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
9:27:45 AM:     at __nccwpck_require__ (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
9:27:45 AM:     at 327 (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
9:27:45 AM:     at __nccwpck_require__ (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
9:27:45 AM:     at 845 (/opt/build/repo/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
9:27:45 AM:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
9:27:45 AM: }
9:27:45 AM: Node.js v18.16.0
9:27:45 AM: ​
9:27:45 AM: "build.command" failed                                        
9:27:45 AM: ────────────────────────────────────────────────────────────────
9:27:45 AM: ​
9:27:45 AM:   Error message
9:27:45 AM:   Command failed with exit code 1: npm run export (https://ntl.fyi/exit-code-1)
9:27:45 AM: ​
9:27:45 AM:   Error location
9:27:45 AM:   In build.command from netlify.toml:
9:27:45 AM:   npm run export
9:27:45 AM: ​
9:27:45 AM:   Resolved config
9:27:45 AM:   build:
9:27:45 AM:     command: npm run export
9:27:45 AM:     commandOrigin: config
9:27:45 AM:     publish: /opt/build/repo/dist
9:27:45 AM:     publishOrigin: config
9:27:49 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:27:49 AM: Failing build: Failed to build site
9:27:49 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:27:50 AM: Finished processing build request in 28.824s
```

**Comment by JorisKok** [comment]
Woops. Wrong repo.
